### PR TITLE
Improved zeus detection

### PR DESCRIPTION
**Pull request by johnb432**
This PR improves curator detection and cleans up some code.
It also adds an `editorconfig` file, which is useful to keep one style of e.g. tabs for the whole project.

### CODE REVIEW

**Comment by Crowdedlight** [comment]
Thank you very much Johnb432! I am currently in Africa doing Humanitarian work with Engineers without Borders. Internet is very sparse here. But I should be able to take a look at it next week. :)

**Comment by windwalker-888** [comment]
hey @johnb432 
am i correct in assuming you load all modules even if the player is not zeus? 
and then the pingbox when one enters the zeus view the first time.

**Comment by Crowdedlight** [comment]
> Yes. I don't think it makes much of a performance difference if you load them, even if you don't use them. However, if you load them, they will always be available when you enter the Zeus interface. As it is now, depending on performance impact you have when entering the Zeus interface, it doesn't always load the modules, meaning you need to refresh the Zeus interface (either via keybind or by exiting and reentering).

The performance doesn't matter much in terms of registering the modules for everyone. Was essentially also what I did initially. I had to move away from it, due to the added features of pingbox and ace-medical-text keybinds which are not modules and if loaded means it could be used without being a zeus. 

I had a quick read of the code, and I like the approach where those things are loaded based on event. I kinda hoped there would be a ``CuratorCreated`` event from arma, to detect when someone was made curator. But detecting entering zeus is the next best thing. I think that almost everyone getting zeus will immediately go into the interface anyway. 

Have you tested this with "ForcedInterface" turned on? I am wondering if the event still fires, or fires too early to catch if you are in a "ForcedInterface" curator. 

I am planning on merging and releasing this weekend. :)

**Comment by Crowdedlight** [comment]
Did test with "ForcedInterface", and it works. Everything seem to work fine. :)

**Pull request merged**
